// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddConnection(arg1:models.Connection):Promise<void>;

export function AddForeignKey(arg1:string,arg2:models.FKDefinition):Promise<void>;

export function AlterTable(arg1:string,arg2:models.TableDefinition,arg3:models.TableDefinition):Promise<Array<string>>;

export function BrowseTable(arg1:string,arg2:string,arg3:string,arg4:models.BrowseOptions):Promise<models.QueryResult>;

export function CancelQuery(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function CreateIndex(arg1:string,arg2:models.IndexDefinition):Promise<void>;

export function CreateTable(arg1:string,arg2:models.TableDefinition):Promise<string>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DropConstraint(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DropIndex(arg1:string,arg2:string):Promise<void>;

export function DropTable(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:number):Promise<models.QueryResult>;

export function ExecuteRawDDL(arg1:string,arg2:string):Promise<void>;

export function ExplainQuery(arg1:string,arg2:string):Promise<models.ExplainResult>;

export function ExportData(arg1:models.QueryResult,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetActiveConnections():Promise<Array<string>>;

export function GetColumns(arg1:string,arg2:string,arg3:string):Promise<Array<models.ColumnInfo>>;

export function GetConnInfo(arg1:string):Promise<string>;

export function GetDatabaseName(arg1:string):Promise<string>;

export function GetDefaultConnectionConfig():Promise<main.DefaultConnectionConfig>;

export function GetForeignKeys(arg1:string,arg2:string,arg3:string):Promise<Array<models.FKInfo>>;

export function GetFullSchema(arg1:string):Promise<Record<string, any>>;

export function GetFunctions(arg1:string,arg2:string):Promise<Array<models.FunctionInfo>>;

export function GetIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<models.IndexInfo>>;

export function GetQueryHistory(arg1:string,arg2:number):Promise<Array<models.QueryHistoryEntry>>;

export function GetSavedQueries():Promise<Array<models.SavedQuery>>;

export function GetSchemas(arg1:string):Promise<Array<models.SchemaInfo>>;

export function GetSearchCatalog():Promise<Array<main.CatalogItem>>;

export function GetSequences(arg1:string,arg2:string):Promise<Array<models.SequenceInfo>>;

export function GetTableDDL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetTables(arg1:string,arg2:string):Promise<Array<models.TableInfo>>;

export function GetTimestamp():Promise<string>;

export function GetTriggers(arg1:string,arg2:string,arg3:string):Promise<Array<models.TriggerInfo>>;

export function GetTypes(arg1:string,arg2:string):Promise<Array<models.TypeInfo>>;

export function GetViews(arg1:string,arg2:string):Promise<Array<models.ViewInfo>>;

export function IsConnected(arg1:string):Promise<boolean>;

export function ListConnections():Promise<Array<models.Connection>>;

export function LoadWorkspace():Promise<string>;

export function RefreshSchema(arg1:string):Promise<void>;

export function RenameTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveQuery(arg1:string,arg2:string):Promise<void>;

export function SaveWorkspace(arg1:string):Promise<void>;

export function SyncPgAdminConnections():Promise<number>;

export function SyncServerConnections():Promise<number>;

export function TestConnection(arg1:models.Connection):Promise<models.ConnectionTestResult>;

export function UpdateConnection(arg1:models.Connection):Promise<void>;
