// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function AddForeignKey(arg1, arg2) {
  return window['go']['main']['App']['AddForeignKey'](arg1, arg2);
}

export function AlterTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['AlterTable'](arg1, arg2, arg3);
}

export function BrowseTable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowseTable'](arg1, arg2, arg3, arg4);
}

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateIndex(arg1, arg2) {
  return window['go']['main']['App']['CreateIndex'](arg1, arg2);
}

export function CreateTable(arg1, arg2) {
  return window['go']['main']['App']['CreateTable'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DropConstraint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DropConstraint'](arg1, arg2, arg3, arg4);
}

export function DropIndex(arg1, arg2) {
  return window['go']['main']['App']['DropIndex'](arg1, arg2);
}

export function DropTable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DropTable'](arg1, arg2, arg3, arg4);
}

export function ExecuteMultipleQueries(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteMultipleQueries'](arg1, arg2, arg3);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExecuteRawDDL(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRawDDL'](arg1, arg2);
}

export function ExplainQuery(arg1, arg2) {
  return window['go']['main']['App']['ExplainQuery'](arg1, arg2);
}

export function ExportData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportData'](arg1, arg2, arg3, arg4);
}

export function GetActiveConnections() {
  return window['go']['main']['App']['GetActiveConnections']();
}

export function GetColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetColumns'](arg1, arg2, arg3);
}

export function GetConnInfo(arg1) {
  return window['go']['main']['App']['GetConnInfo'](arg1);
}

export function GetDatabaseName(arg1) {
  return window['go']['main']['App']['GetDatabaseName'](arg1);
}

export function GetDefaultConnectionConfig() {
  return window['go']['main']['App']['GetDefaultConnectionConfig']();
}

export function GetForeignKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetForeignKeys'](arg1, arg2, arg3);
}

export function GetFullSchema(arg1) {
  return window['go']['main']['App']['GetFullSchema'](arg1);
}

export function GetFunctions(arg1, arg2) {
  return window['go']['main']['App']['GetFunctions'](arg1, arg2);
}

export function GetIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetIndexes'](arg1, arg2, arg3);
}

export function GetQueryHistory(arg1, arg2) {
  return window['go']['main']['App']['GetQueryHistory'](arg1, arg2);
}

export function GetSavedQueries() {
  return window['go']['main']['App']['GetSavedQueries']();
}

export function GetSchemas(arg1) {
  return window['go']['main']['App']['GetSchemas'](arg1);
}

export function GetSearchCatalog() {
  return window['go']['main']['App']['GetSearchCatalog']();
}

export function GetSequences(arg1, arg2) {
  return window['go']['main']['App']['GetSequences'](arg1, arg2);
}

export function GetTableDDL(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableDDL'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function GetTimestamp() {
  return window['go']['main']['App']['GetTimestamp']();
}

export function GetTriggers(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTriggers'](arg1, arg2, arg3);
}

export function GetTypes(arg1, arg2) {
  return window['go']['main']['App']['GetTypes'](arg1, arg2);
}

export function GetViews(arg1, arg2) {
  return window['go']['main']['App']['GetViews'](arg1, arg2);
}

export function IsConnected(arg1) {
  return window['go']['main']['App']['IsConnected'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function LoadWorkspace() {
  return window['go']['main']['App']['LoadWorkspace']();
}

export function RefreshSchema(arg1) {
  return window['go']['main']['App']['RefreshSchema'](arg1);
}

export function RenameTable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameTable'](arg1, arg2, arg3, arg4);
}

export function SaveQuery(arg1, arg2) {
  return window['go']['main']['App']['SaveQuery'](arg1, arg2);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function SyncPgAdminConnections() {
  return window['go']['main']['App']['SyncPgAdminConnections']();
}

export function SyncServerConnections() {
  return window['go']['main']['App']['SyncServerConnections']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}
